staking fixes
EveripediaNetwork/iq-ui pull request #13
Opened 2022-07-26 13:42 UTC by anubra266

Staking page fixes from review

2022-07-26 14:46 UTC, Simplypheyie96 requested changes
The changes are highlighted in the pictures below.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/99387231/181037300-e335c696-bd66-4d4a-8489-8a50dc4f8b61.png">

2022-07-26 22:39 UTC, anubra266 commented
@Simplypheyie96 look the size we have in figma.
<img width="442" alt="CleanShot 2022-07-26 at 23 38 30@2x" src="https://user-images.githubusercontent.com/30869823/181124290-0c2df052-e642-4cbe-9772-0fd390fb17fe.png">

2022-07-26 22:44 UTC, anubra266 commented on src/components/icons/uniswap-ellipse.tsx
> +      />
```suggestion
      />
      <circle cx="12" cy="12" r="12" fill="#FF007A" fillOpacity="0.2" />

2022-07-27 12:52 UTC, Simplypheyie96 commented
> ****

i don't know why that is showing you that. Please adjust as corrected
![image](https://user-images.githubusercontent.com/99387231/181251166-936c0442-c165-4eb8-b3dc-8a8e3fb29315.png)
![image](https://user-images.githubusercontent.com/99387231/181251363-5fca0f9b-a740-4ced-8be9-22e25ef48529.png)

2022-07-27 12:56 UTC, Simplypheyie96 commented
@anubra266 please, always check figma well, i just realized you used the md breakpoint for the desktop to implement this. Do another check on figma with the correct labels

2022-07-29 07:10 UTC, Simplypheyie96 requested changes
some fixes from the old review are yet to be attended to.
background color, the missing and the wrong icons

2022-07-29 07:38 UTC, anubra266 commented
<img width="548" alt="CleanShot 2022-07-29 at 08 32 53@2x" src="https://user-images.githubusercontent.com/30869823/181708244-0c18d459-0556-45f8-b732-24d5f702db4c.png">

@Simplypheyie96 The icon part is not clear. The user has to know when a ascending or descending sort is on, and when sort is off. Also, you didn't provide separate icons, the two are one svg. 
And if you tested the sort, you'll have seen that there are no icons by default, cause the data shouldn't be sorted by default. If you clicked any of the headers, it would be sorted and the icons would come up.

2022-07-29 07:55 UTC, Simplypheyie96 commented
> <img alt="CleanShot 2022-07-29 at 08 32 53@2x" width="548" src="https://user-images.githubusercontent.com/30869823/181708244-0c18d459-0556-45f8-b732-24d5f702db4c.png">
> 
> @Simplypheyie96 The icon part is not clear. The user has to know when a ascending or descending sort is on, and when sort is off. Also, you didn't provide separate icons, the two are one svg. And if you tested the sort, you'll have seen that there are no icons by default, cause the data shouldn't be sorted by default. If you clicked any of the headers, it would be sorted and the icons would come up.

i don't think that the ascending and descending sort is something on the design end. I can get you thesvg tho on figma beside the staking page. 
![image](https://user-images.githubusercontent.com/99387231/181711948-9ba4c456-aa91-4ff9-8eac-3cebcbfb8de0.png)

2022-07-29 08:05 UTC, anubra266 commented
@Simplypheyie96 I already figured out a way to get the separate svgs. Also I made some changes to show sort status with the icon colors. Check them out and lemme know if it's fine by you.

2022-08-04 09:06 UTC, kesar approved these changes

2022-08-04 09:11 UTC, merged