Daily treasury graph
EveripediaNetwork/iq-ui pull request #159
Opened 2023-07-12 17:40 UTC by Emmanueldmlr

# Daily treasury graph

_On the Treasury page, we need to design a graph that gives the data of the daily treasury value.

this graph should be positioned above the NFT images and the size of the nft should be relatively reduced.

fixes https://github.com/EveripediaNetwork/issues/issues/1542

2023-07-13 10:55 UTC, kesar commented
you should consider having linters properly installed on your IDE / pre commit hooks :P

2023-07-13 11:25 UTC, Simplypheyie96 requested changes
Doesn't look good on mobile ![Screenshot_20230713_122009_Chrome.jpg](https://github.com/EveripediaNetwork/iq-ui/assets/99387231/8626cfcb-5059-492b-981c-d1e54577d766)

- shouldn't this be in dollars?![20230713_122312.jpg](https://github.com/EveripediaNetwork/iq-ui/assets/99387231/238eb219-9169-4642-a3ae-a8d92e3ede13)

-then the token symbols are missing on the vertical sides of the graph (noticed this on the dashboard too for iq staked)

- the nfts should have similar animation to wikis on iq wiki where they change at interval.

2023-07-15 18:47 UTC, OleanjiKingCode commented on src/app/dashboard/page.tsx
> +              })}
The graph component from line 167- 288 can be reduced using the  <GraphComponent/>

2023-07-15 18:47 UTC, OleanjiKingCode commented on src/utils/treasury-utils.ts
> +// export const getCurrentPageData = (
this part of the code is commented not sure we are still using this

2023-07-15 18:47 UTC, OleanjiKingCode commented on src/theme/semantic-tokens.ts
> +      default: 'whiteAlpha.900',
The color for this toolTipBg already exists in line 147-150 and the dark is gray 700 from the design

2023-07-15 18:51 UTC, OleanjiKingCode commented
- The graph and nft carousel look in a lesser screen size


![image](https://github.com/EveripediaNetwork/iq-ui/assets/75235148/8840bc9f-e349-48ad-8150-9002e54c9e53)


- Different price timestamps options than in design

![image](https://github.com/EveripediaNetwork/iq-ui/assets/75235148/e262a768-19c6-488a-b4e9-587f33f79b20)


- Timestamp price options doesn't change the graph look when clicked

![image](https://github.com/EveripediaNetwork/iq-ui/assets/75235148/f60e1c88-992d-4843-bd2e-c037ecd75b1a)

![image](https://github.com/EveripediaNetwork/iq-ui/assets/75235148/67eb5582-1779-4c5c-93a0-a070ea424133)

2023-07-17 21:10 UTC, OleanjiKingCode approved these changes

2023-07-17 21:41 UTC, merged