Iteration on the homepage
EveripediaNetwork/iq-ui pull request #160
Opened 2023-07-15 16:08 UTC by Emmanueldmlr

# Iteration on the homepage

_On the Dashboard page, let's have a way to connect the IQ stat with the homepage of the Dashboard. Probably we can have a "view more' text or button that links to the IQ Stat page. and perhaps we could have a link that connects to fraxswap too

fixes https://github.com/EveripediaNetwork/issues/issues/1541

2023-07-19 21:09 UTC, Emmanueldmlr commented
1) I think you need to align them properly
<img width="436" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/70170061/36516f74-a873-49c4-ba7a-faa03d5aaaa6">
2) Resolve the Ens name of the addresses
3) Link the addresses to etherscan

2023-07-21 09:01 UTC, Simplypheyie96 requested changes
it's broken on mobile view
<img width="393" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/99387231/3108fc12-7672-4add-9ac1-20f37618b8ed">

2023-07-21 10:34 UTC, Simplypheyie96 approved these changes

2023-07-21 10:35 UTC, Emmanueldmlr commented
LGTM

2023-07-21 10:40 UTC, merged