Refactoring IQ UI Pages
EveripediaNetwork/iq-ui pull request #175
Opened 2023-07-29 16:00 UTC by OleanjiKingCode

# Refactoring IQ UI pages 

_This pr refactors some iq ui pages and does others like:_

- Remove unused comments
- create files for types of components
- rename variables/folders

2023-07-31 10:21 UTC, Emmanueldmlr requested changes

2023-09-05 10:59 UTC, Royal-lobster commented
yeah its been over month. @Emmanueldmlr can we close this ?

2023-09-05 13:20 UTC, Softdev1 commented
> Yeah its been over a month. @Emmanueldmlr can we close this?

@SidharthK2  will have to check it since @Emmanueldmlr  is currently on leave

2023-09-05 14:05 UTC, SidharthK2 commented
> > Yeah its been over a month. @Emmanueldmlr can we close this?
> 
> @SidharthK2 will have to check it since @Emmanueldmlr is currently on leave

We should merge the IQ Token Holder graph branch first, then I can look at the conflicts.

2023-10-09 10:23 UTC, closed without merging