Adds custom 404 page
EveripediaNetwork/iq-ui pull request #253
Opened 2024-04-17 09:52 UTC by SidharthK2

# Adds custom 404 page
- 
![image](https://github.com/EveripediaNetwork/iq-ui/assets/58448956/8e16a749-4f66-476c-9de2-4149df6ec132)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2524

2024-04-17 11:04 UTC, Simplypheyie96 requested changes
- The font weight should be medium.
also, make it 2 lines without living orphans in the typography.
<img width="980" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/99387231/5c5519f8-564b-440c-85d3-3f201781564e">

2024-04-17 12:42 UTC, Simplypheyie96 commented
<img width="913" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/99387231/e6338346-2b75-46ca-acf9-f4d5ec0e7c70">

there is still an orphan in the typography. Either make it 2 lines, or reduce the width of the text to avoid orphans to something like this:
<img width="814" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/99387231/46c3d06d-31d9-4bb9-b097-0b1defa7f6e9">
@SidharthK2

2024-04-17 13:22 UTC, SidharthK2 commented
> <img alt="image" width="913" src="https://private-user-images.githubusercontent.com/99387231/323220172-e6338346-2b75-46ca-acf9-f4d5ec0e7c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkwNzcsIm5iZiI6MTcxMzM1ODc3NywicGF0aCI6Ii85OTM4NzIzMS8zMjMyMjAxNzItZTYzMzgzNDYtMmI3NS00NmNhLWFjZjktZjRkNWVjMGU3YzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZDE0ZTIxOWEzNjI5YjA5MDZjYzczYzBmNmJhNmQxY2QzNzFhMzhkNzBlY2E5NTAwYjMzNTBmMTU4YTYwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ccWqbaTBRBczvh50zpsN3ChFpeRN0moHL2VV33siFMw">
> there is still an orphan in the typography (browsing sitting alone in the third line). Either make it 2 lines, or reduce the width of the text to avoid orphans to something like this: <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/99387231/323220694-46c3d06d-31d9-4bb9-b097-0b1defa7f6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkwNzcsIm5iZiI6MTcxMzM1ODc3NywicGF0aCI6Ii85OTM4NzIzMS8zMjMyMjA2OTQtNDZjM2QwNmQtMzFkOS00YmI5LWIwOTctMGIxZGVmYTdmNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNWYxMzllYWEyNjRiMzBlYzIwNDhhYzAwODkzOGYzMTJkZDNiYzJlMTViMjZmZGJiZDZjNjI4Mzk0YWQyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVjK4oig1OE8pCQQQeE41_AK4RTkqn9u_SpnS7r2YUg"> @SidharthK2

Alright, which breakpoint are you encountering this on?

2024-04-17 16:49 UTC, Simplypheyie96 approved these changes

2024-04-18 09:55 UTC, Aliiiu approved these changes

2024-04-18 10:34 UTC, merged