voting fixes
EveripediaNetwork/iq-ui pull request #26
Opened 2022-08-05 04:38 UTC by anubra266

FIxes EveripediaNetwork/issues#590

2022-08-05 05:21 UTC, anubra266 commented
Hi @kesar I want to consume the API used here: https://snapshot.everipedia.com/#/ for the IQ voting page, I don't know what API I'm to use.

2022-08-09 08:59 UTC, kesar commented
> Hi @kesar I want to consume the API used here: https://snapshot.everipedia.com/#/ for the IQ voting page, I don't know what API I'm to use.

https://www.google.com/search?q=snapshot.org+api

2022-08-15 22:26 UTC, Simplypheyie96 requested changes
a little space below the end of the page so as not to cut the cards
![image](https://user-images.githubusercontent.com/99387231/184727169-59623200-22e6-442a-997d-7acbd3fc037b.png)

the dividing line doesn't reach the end of the page
![image](https://user-images.githubusercontent.com/99387231/184727423-f38bfd72-f291-419e-96e9-944d387e87ee.png)

so the cards are showing this way for me.
![image](https://user-images.githubusercontent.com/99387231/184728798-65522ba4-c76d-472f-86ac-afa461be4756.png)
what we can do is show the contract address this way: 
![image](https://user-images.githubusercontent.com/99387231/184729190-352ee5ee-7198-42f1-834d-18d0c8bc8657.png)
because on the design on figma, that wasn't designed with contract address in mind but a full name. like this 
![image](https://user-images.githubusercontent.com/99387231/184729578-3f253991-321f-4121-bf9b-6b4257e911db.png)

also, this section is too narrow. check swap page for reference
![image](https://user-images.githubusercontent.com/99387231/184730785-491e3b37-120f-4a06-85f6-6ce534fe010f.png)

the whole voting page looks like this on mobile
![image](https://user-images.githubusercontent.com/99387231/184731299-02ace9d9-253f-419e-8fc7-3a5dd5b48cc2.png)

2022-08-15 22:49 UTC, Simplypheyie96 approved these changes

2022-08-15 22:52 UTC, Emmanueldmlr approved these changes

2022-08-15 22:53 UTC, merged