Treasury mobile UI
EveripediaNetwork/iq-ui pull request #268
Opened 2024-05-27 09:52 UTC by Damola18

# Fixing the Treasury mobile UI

This PR made changes to the NFT image on mobile , modifies the text size inside pie chart and changed the position  

## How should this be tested?

Go to treasury page and switch to mobile orientation to test

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2703

![image](https://github.com/EveripediaNetwork/iq-ui/assets/50779080/e6b13ec4-ca56-44cd-bfd7-28de829f03ec)

![image](https://github.com/EveripediaNetwork/iq-ui/assets/50779080/18043dbe-ff5b-45f3-abf1-1eaab44a3024)

2024-05-27 10:05 UTC, Simplypheyie96 requested changes
- This cut out is still part of the fix. It's yet to be resolved.
![image](https://github.com/EveripediaNetwork/iq-ui/assets/99387231/0f06726b-2f82-4d1c-98b0-01bd80d976dd)
- Graph for total token value is missing too
- The nft display is still kind of weird.
it should look like this:

<img width="573" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/99387231/94837762-71fc-4cca-8d3a-82f4b71fe7e5">

2024-05-30 09:24 UTC, Simplypheyie96 approved these changes

2024-05-30 09:48 UTC, Damola18 commented
> <img alt="image" width="565" src="https://private-user-images.githubusercontent.com/67792966/335130559-c107ea79-2149-4ae7-af5a-da03ad5a9f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjI2OTcsIm5iZiI6MTcxNzA2MjM5NywicGF0aCI6Ii82Nzc5Mjk2Ni8zMzUxMzA1NTktYzEwN2VhNzktMjE0OS00YWU3LWFmNWEtZGEwM2FkNWE5ZjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTY2MWVmMDJlZWQyYmE0ZTE1YjdmNmI2MTdmMWU3OGE3N2FiYTg1MzhlNmZkZTkxYjAyNGIwZWMzNjVkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5z4h-a51pSE5JBJeseXZWq4ywe2-8oFewyFE7g-I5ZM">
> @Simplypheyie96 Is this the right view?

I am checking this now

2024-05-30 09:50 UTC, Simplypheyie96 commented
> <img width="565" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/67792966/c107ea79-2149-4ae7-af5a-da03ad5a9f8d">
> 
> @Simplypheyie96 Is this the right view?

It looks fine on my end 
![Screenshot_20240530_104842_Chrome.jpg](https://github.com/EveripediaNetwork/iq-ui/assets/99387231/7432a196-3093-49a1-8db2-3de45a3774ad)

2024-05-30 10:01 UTC, Damola18 commented
> > <img alt="image" width="565" src="https://private-user-images.githubusercontent.com/67792966/335130559-c107ea79-2149-4ae7-af5a-da03ad5a9f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjI2OTcsIm5iZiI6MTcxNzA2MjM5NywicGF0aCI6Ii82Nzc5Mjk2Ni8zMzUxMzA1NTktYzEwN2VhNzktMjE0OS00YWU3LWFmNWEtZGEwM2FkNWE5ZjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTY2MWVmMDJlZWQyYmE0ZTE1YjdmNmI2MTdmMWU3OGE3N2FiYTg1MzhlNmZkZTkxYjAyNGIwZWMzNjVkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5z4h-a51pSE5JBJeseXZWq4ywe2-8oFewyFE7g-I5ZM">
> > @Simplypheyie96 Is this the right view?
> 
> I am checking this now


![image](https://github.com/EveripediaNetwork/iq-ui/assets/50779080/a56c6e0e-b909-41b5-884b-955da5d00b6a)

2024-05-30 10:29 UTC, Softdev1 approved these changes
<img width="323" alt="image" src="https://github.com/EveripediaNetwork/iq-ui/assets/32770520/d28c427f-46de-4995-a4e0-de2db85380e7">

2024-05-30 10:51 UTC, Aliiiu approved these changes

2024-05-30 11:58 UTC, Damola18 commented on src/components/client/TreasuryPage.tsx
> +                  display={{ base: 'block' }}
Oh, i am using the base: block because i am targeting using the Box within a breakpoint, so i cant use display={'block'} here

2024-05-30 11:58 UTC, merged