Trasure revamp
EveripediaNetwork/iq-ui pull request #50
Opened 2022-09-20 08:23 UTC by Emmanueldmlr

# Treasury Revamp

nfts:
- [x] there are 3 monkeys, it should be one, and 2 placeholders. They should link to opensea Url NFT on mobile it should only show 1 monkey

tokens:
- [ ] the amount of tokens is wrong, those are not the ones that are in the treasury

- [x] graph chart is broken

- [ ] lp tokens (tokens w 2 tokens inside needs proper icons and proper values) <- that's the most complex, we can go w that AFTER everything else is solved
## Linked issues

fixes https://github.com/EveripediaNetwork/issues/issues/618

2022-09-21 15:55 UTC, Emmanueldmlr commented
@Simplypheyie96, kindly let me know when the Loader is ready.

2022-09-21 17:12 UTC, Simplypheyie96 commented
> @Simplypheyie96, kindly let me know when the Loader is ready.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/99387231/191568598-ede0f040-7daa-449b-b1f8-4caa124acdd2.png">

2022-09-22 01:00 UTC, anubra266 requested changes

2022-09-22 14:19 UTC, kesar commented
lets fix conflicts and merge 🔥

2022-09-22 14:26 UTC, Simplypheyie96 approved these changes

2022-09-22 14:31 UTC, merged